server:
  port: 8001
spring:
  application:
    name: grow-analytics-log-server

eureka:
  instance:
    prefer-ip-address: true # 使用IP进行注册
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
